version: "3.7"
services:
    postgres:
        image: postgres:alpine
        container_name: postgres-electricity
        environment: 
            POSTGRES_USER: 'user'
            POSTGRES_PASSWORD: 'password'
            POSTGRES_DB: 'myBusinessdb'
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
volumes:
  pgdata:
    driver: local