service: anotherOne
plugins:
  - serverless-offline
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
functions:
  up:
    handler: up.handler
    events:
      - http:
          method: GET
          path: /
          cors: true
  greet:
    handler: greet.handler
    events:
      - http:
          method: GET
          path: /greet/{NAME}
          cors: true
  check:
    handler: check.handler
    events:
      - http:
          method: POST
          path: /check/{AGE}
          cors: true  