@host=http://localhost:3000
@awshost=https://x2kzg20gw3.execute-api.eu-west-2.amazonaws.com


GET {{host}}/local/live


###

GET {{host}}/local/greet/sotiris

###

POST {{host}}/local/age-restriction/18
content-type: application/json

{
    "name": "sotiris",
    "surname": "loizou"
}
###
POST {{host}}/local/age-restriction/12
content-type: application/json

{
    "name": "sotiris",
    "surname": "loizou"
}
###

POST {{host}}/local/age-restriction/17
content-type: application/json

{
    "name": "sotiris",
    "surname": "loizou"
} 
###

POST {{host}}/local/age-restriction/20
content-type: application/json

{
    "name": "sotiris",
    "surname": "loizou"
}


###

POST {{host}}/local/age-restriction/17
content-type: application/json

{
    "fasd": "sotiris",
    "surname": "loizou"
}
###

POST {{host}}/local/age-restriction/17
content-type: application/json

{
    "name": "sotiris",
    "afss": "loizou"
}

###

POST {{host}}/local/age-restriction/17
content-type: application/json

{
    "fasd": "sotiris",
    "fas": "loizou"
}

###
POST {{host}}/local/customer/12345
content-type: application/json

{
    "name": "sotiris",
    "surname": "loizous",
    "birthYear":1900
}

###
GET {{host}}/local/customer/12345

###
GET {{host}}/local/customer/2

###
GET {{host}}/local/customer/afsd

###
POST {{host}}/local/strict-customer/11111
content-type: application/json

{
    "name": "sotiris",
    "surname": "loizous",
    "birthYear": "1900"
}
###
POST {{host}}/local/strict-customer/22222
content-type: application/json

{
    "name": "andreas",
    "surname": "antoniou",
    "birthYear": "2000"
}
###
POST {{host}}/local/customer/33333
content-type: application/json

{
    "name": "john",
    "surname": "white",
    "email":"johnwhite@ola.com",
    "birthYear": 2002
}
###
POST {{host}}/local/customer/11111
content-type: application/json

{
    "name": "sotiris",
    "surname": "loizou",
    "birthYear": "1000"
}
###
POST {{host}}/local/customer/632541
content-type: application/json

{
    "name": "omer",
    "surname": "job",
    "email":"omerjob@yahoo.com",
    "birthYear": "2002"
}
###
DELETE {{host}}/local/customer/22222

###
GET {{host}}/local/customer/22222
###
POST {{host}}/local/strict-customer/2345234
content-type: application/json

{
    "name": "tofias",
    "surname": "raxous",
    "birthYear": "2005"
}
###

POST {{host}}/local/customer/12
content-type: application/json

{
    "name": "tofias",
    
    "birthYear": "2005"
}
###
GET {{host}}/local/customer/22222

###
POST https://x2kzg20gw3.execute-api.eu-west-2.amazonaws.com/local/strict-customer/12345
content-type: application/json

{
    "name": "jonhy",
    "surname": "leviathan",
    "birthYear": "2000"
}
###
GET {{host}}/local/customer/22222

###
GET {{host}}/local/get-strict-customer/2

###
GET {{host}}/local/get-strict-customer/fasd


###
GET {{host}}/local/file/fileMark.json

###
POST {{host}}/local/file/fileMark.json
content-type: application/json

{
    "name": "Mark",
    "birthCity": "Londona",
    "countryOrigin": "England",
    "languages": ["English","Russian","German"],
    "birthYear": "2005"
}

###
POST {{host}}/local/customer/file-image/aChar.jpg
