@host=http://localhost:3000


GET {{host}}/dev/live


###

GET {{host}}/dev/greet/sotiris

###

POST {{host}}/dev/age-restriction/18
content-type: application/json

{
    "name": "sotiris",
    "surname": "loizou"
}

###

POST {{host}}/dev/age-restriction/17
content-type: application/json

{
    "name": "sotiris",
    "surname": "loizou"
} 
###

POST {{host}}/dev/age-restriction/fasd
content-type: application/json

{
    "name": "sotiris",
    "surname": "loizou"
}


###

POST {{host}}/dev/age-restriction/17
content-type: application/json

{
    "fasd": "sotiris",
    "surname": "loizou"
}
###

POST {{host}}/dev/age-restriction/17
content-type: application/json

{
    "name": "sotiris",
    "afss": "loizou"
}

###

POST {{host}}/dev/age-restriction/17
content-type: application/json

{
    "fasd": "sotiris",
    "fas": "loizou"
}

###
POST {{host}}/dev/customer/1
content-type: application/json

{
    "name": "sotiris",
    "surname": "loizou"
}

###
GET {{host}}/dev/customer/1

###
GET {{host}}/dev/customer/2

###
GET {{host}}/dev/customer/fasd

###
POST {{host}}/dev/strict-customer/22341
content-type: application/json

{
    "name": "sotiris",
    "surname": "loizou",
    "birth_year": "1900"
}

###
GET {{host}}/dev/get-strict-customer/22341

###
GET {{host}}/dev/get-strict-customer/2

###
GET {{host}}/dev/get-strict-customer/fasd